// ============================================================
// API 统一导出入口
// 用法: import { taskApi, documentApi } from '@/api'
// ============================================================
export * from './http'
export { authApi } from './auth'
export { taskApi } from './task'
export { documentApi } from './document'
export { conversationApi, aiApi } from './conversation'
export { reviewApi } from './review'
export { dashboardApi, backupApi } from './dashboard'
export { panelApi } from './panel'
export { notificationApi } from './notification'
export { projectApi } from './project'

export { resourceApi } from './resource'
export { learningApi } from './learning'
export { lifeApi } from './life'
export { assetApi } from './asset'
export { growthApi } from './growth'
export { petApi } from './pet'
export { systemApi } from './system'
export { settingsApi, NOTIFY_KEYS } from './settings'
export { identityApi } from './identity'
export { experienceApi } from './experience'
export { workspaceApi } from './workspace'
export { reportApi } from './report'
export { vaultApi } from './vault'
export { aihotApi } from './aihot'
export { syncApi } from './sync'
export type { SettingsValues } from './settings'
