/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./components/common/AppIcon.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppTitleBar: typeof import('./components/layout/AppTitleBar.vue')['default']
    BaseBreadcrumb: typeof import('./components/layout/BaseBreadcrumb.vue')['default']
    BaseButton: typeof import('./components/common/BaseButton.vue')['default']
    BaseCard: typeof import('./components/common/BaseCard.vue')['default']
    BaseConfirm: typeof import('./components/common/BaseConfirm.vue')['default']
    BaseDrawer: typeof import('./components/common/BaseDrawer.vue')['default']
    BaseEmpty: typeof import('./components/common/BaseEmpty.vue')['default']
    BaseInput: typeof import('./components/common/BaseInput.vue')['default']
    BaseModal: typeof import('./components/common/BaseModal.vue')['default']
    BasePagination: typeof import('./components/common/BasePagination.vue')['default']
    BaseSelect: typeof import('./components/common/BaseSelect.vue')['default']
    BaseSkeleton: typeof import('./components/common/BaseSkeleton.vue')['default']
    BaseSwitch: typeof import('./components/common/BaseSwitch.vue')['default']
    BaseTag: typeof import('./components/common/BaseTag.vue')['default']
    BaseToast: typeof import('./components/common/BaseToast.vue')['default']
    BaseTooltip: typeof import('./components/common/BaseTooltip.vue')['default']
    CommandPalette: typeof import('./components/layout/CommandPalette.vue')['default']
    DefaultLayout: typeof import('./components/layout/DefaultLayout.vue')['default']
    DesktopPet: typeof import('./components/pet/DesktopPet.vue')['default']
    FocusTimer: typeof import('./components/task/FocusTimer.vue')['default']
    GlobalSearch: typeof import('./components/layout/GlobalSearch.vue')['default']
    LeftInfoPanel: typeof import('./components/layout/LeftInfoPanel.vue')['default']
    ModalHost: typeof import('./components/common/ModalHost.vue')['default']
    ModalItem: typeof import('./components/common/ModalItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarFooter: typeof import('./components/layout/SidebarFooter.vue')['default']
    ToastItem: typeof import('./components/common/ToastItem.vue')['default']
    TopNav: typeof import('./components/layout/TopNav.vue')['default']
    WindowStatusIndicator: typeof import('./components/layout/WindowStatusIndicator.vue')['default']
  }
}
